### ISSUE TITLE
iOS 12 Safari breaks ASP.NET Core OIDC authentication

### ISSUE THREAD

**Issue by rhysawilliams2010** [aspnet/AADIntegration#52]
When logging into a site using Azure AD B2C Auth flow on IOS 12 I get caught in an infinite loop between my site and login.microsoft.com.

The application works fine on other browsers and operating systems.

I believe the issue may be related to:
- https://social.msdn.microsoft.com/Forums/en-US/5f0aa4a8-9bfe-4be2-a366-77e6939ae36d/ios-12-safari-breaks-aspnet-core-21-oidc-authentication?forum=WindowsAzureAD&prof=required
- https://bugs.webkit.org/show_bug.cgi?id=188165
- https://hajekj.net/2018/08/31/beware-of-samesite-cookie-policy-in-asp-net-core-and-upcoming-ios-12/

As an interim fix I have set ```o.Cookie.SameSite = SameSiteMode.None;``` but this seems like a pretty suboptimal approach.

Is there a better solution?

**Comment by thdotnet** [comment]
@rhysawilliams2010 where did you put this setting? I've tried, but it keeps as SameSite.Lax:

```
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => {
                    Configuration.Bind("AzureAd", options);
                })
                .AddCookie(options=>
                        options.Cookie.SameSite = SameSiteMode.None
                    );


```
and 

```
app.UseCookiePolicy(new CookiePolicyOptions
            {                
                MinimumSameSitePolicy = SameSiteMode.None
            });

```

**Comment by rosskyl** [comment]
I was having the same problems and solved it by creating a `CookieAuthenitcationOptions` object and adding a singleton to the services before adding authentication. Below is what I have in my startup class.

```
public void ConfigureServices(IServiceCollection services)
{
	//Added these lines of code
	CookieAuthenticationOptions cookieOptions = new CookieAuthenticationOptions()
	{
		Cookie = new CookieBuilder()
		{
			SameSite = SameSiteMode.None
		}
	};
	services.AddSingleton(cookieOptions);

	var loggerFactory = new LoggerFactory();

	services.AddAuthentication(sharedOptions =>
	{
		sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
		sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
	})
	.AddAzureAd(options =>
	{
		Configuration.Bind("AzureAd", options);
		AzureAdOptions.Settings = options;
	})
	//Added the options portion
	.AddCookie(options => options.Cookie.SameSite = SameSiteMode.None);

	...
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	//Added this part
	app.UseCookiePolicy(new CookiePolicyOptions()
	{
		MinimumSameSitePolicy = SameSiteMode.None
	});

	app.UseSession(); // Needs to be app.UseAuthentication() and app.UseMvc() otherwise you will get an exception "Session has not been configured for this application or request."
	app.UseAuthentication();

	app.UseMvc(routes =>
	{
		routes.MapRoute(
			name: "default",
			template: "{controller=Home}/{action=Index}/{id?}");
	});
}
```

**Comment by thdotnet** [comment]
services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
            });

worked for me
